GRE-106 add color processing
sknowlton-everi/GliToJiraImporter pull request #19
Opened 2023-03-01 21:45 UTC by sknowlton-everi

2023-03-01 22:05 UTC, roatanrich requested changes
make sure to add requested comments and test categories

2023-03-02 19:20 UTC, sknowlton-everi commented on GliToJiraImporter.Testing/Tests/ParserTester.cs
> +        [Ignore("This test is very large and takes a long time to complete.")]
That message should have been changed has it isn't accurate. It has been fixed

2023-03-02 19:21 UTC, sknowlton-everi commented on GliToJiraImporter/Parsers/Parser.cs
> +                    j--;
Good call, I added comments to all the ones I could remember

2023-03-02 19:21 UTC, sknowlton-everi commented on GliToJiraImporter/Parsers/RegulationParser.cs
> +                                i--;
Done

2023-03-02 19:22 UTC, sknowlton-everi commented on GliToJiraImporter/Parsers/Parser.cs
> +                WTableCell firstCell = tables[i].Rows[0].Cells[0];
I was hoping the name would be enough as you have mentioned a preference for that before. Comment added, let me know if it's okay

2023-03-02 20:30 UTC, merged